BLUE_CONE_STYLE = 0
YELLOW_CONE_STYLE = 1
ORANGE_CONE_STYLE = 2
BIG_CONE_STYLE = 3
UNKNOWN_CONE_STYLE = 4

CONE_FIELD_OF_VIEW = 360
CONE_DISTANCE = 10
WAYPOINT_FIELD_OF_VIEW = 180
WAYPOINT_DISTANCE = 3
MAX_SEARCH_ITERATIONS = 3
PATH_QUEUE_LIMIT = 1
MAX_WAYPOINTS_PER_PATH = 3

DIST_TRIANGULATE = 1
DIST_TRIANGULATE2 = 1

TRACKWIDTH = 4
LARGEST_ANGLE_CHANGE_WEIGHT = 1
TRACK_WIDTH_WEIGHT = 4
MAX_DIST_WEIGHT = 0.0
LENGTH_WEIGHT = 1/1.8
LENGTH_WEIGHT = 0
ERROR_NO_DETECT = 4
COLOR_WEIGHT = 1
NEW_POINTS_RADIUS = TRACKWIDTH/2 - 0.1
